# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 18:33
from __future__ import unicode_literals

import ckeditor.fields
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Навзвание ')),
                ('type', models.CharField(choices=[('main', 'Главная'), ('mid', 'Средняя'), ('big', 'Большая'), ('mini', 'Маленькая')], default='mid', max_length=4, verbose_name='Тип')),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(verbose_name='Статья')),
                ('short_description', models.TextField(default='', verbose_name='Короткое описание')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='Изображение')),
                ('size', models.IntegerField(choices=[(50, 'Большая'), (25, 'Средняя')], default=25, verbose_name='Размер')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('page', models.IntegerField(default=0, verbose_name='Страница')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField()),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
            options={
                'verbose_name': 'Категория',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
