# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 05:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='\u041d\u0430\u0432\u0437\u0432\u0430\u043d\u0438\u0435 ')),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
            },
        ),
    ]
