# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Статья'},
        ),
    ]
