# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180426_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_hash',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
