# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_hash',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
