# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180429_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default=0, max_length=255, upload_to=''),
        ),
    ]
