# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 20:53
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180429_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to=blog.models.Article.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default=0, max_length=255, null=True, upload_to=''),
        ),
    ]
