# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180429_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hash',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
