# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='line_num',
            field=models.IntegerField(default=0, verbose_name='Линия размещения'),
        ),
        migrations.AddField(
            model_name='article',
            name='order_in_line',
            field=models.IntegerField(default=0, verbose_name='Порядок в линии'),
        ),
    ]
