# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='size',
            field=models.IntegerField(choices=[(50, 'Большая'), (25, 'Средняя')], default=25, verbose_name='Размер'),
        ),
    ]
