# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_article_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(default='', verbose_name='Короткое описание'),
        ),
    ]
