# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.IntegerField(default=0, verbose_name='Страница'),
        ),
    ]
