# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Category', verbose_name='Категория'),
        ),
    ]
