# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 12:12
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AddField(
            model_name='event',
            name='internet_available',
            field=models.BooleanField(default=True, verbose_name='Есть доступ к интернету'),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AddField(
            model_name='event',
            name='take_computer',
            field=models.BooleanField(default=True, verbose_name='Брать компьютер'),
        ),
        migrations.AddField(
            model_name='event',
            name='value',
            field=models.CharField(default='Бесплатно', max_length=300, verbose_name='Стоимость'),
        ),
    ]
