# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180225_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=300, verbose_name='Место'),
        ),
    ]
