# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='take_computer',
            field=models.CharField(default=True, max_length=300, verbose_name='Брать компьютер'),
        ),
    ]
