# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20180225_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='internet_available',
            field=models.CharField(choices=[('Есть', 'Есть'), ('Может есть', 'Может есть'), ('Может есть, а может нет', 'Может есть, а может нет'), ('Ну такое', 'Ну такое'), ('Скорее да, чем нет', 'Скорее да, чем нет'), ('Скорее нет, чем да', 'Скорее нет, чем да'), ('Нет', 'Нет')], default=True, max_length=300, verbose_name='Есть доступ к интернету'),
        ),
        migrations.AlterField(
            model_name='event',
            name='take_computer',
            field=models.CharField(choices=[('Да', 'Да'), ('Может понадобиться', 'Может понадобиться'), ('Нет', 'Нет')], default=True, max_length=300, verbose_name='Брать компьютер'),
        ),
    ]
