# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180428_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_nework',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
