# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180222_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Фотография'),
        ),
    ]
