# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='social_nework',
            field=models.ManyToManyField(to='accounts.SocialNetwork'),
        ),
    ]
